### ISSUE TITLE
Renovations of the project

### ISSUE THREAD

**Issue by mdeweerd** [Madic-/ipxe-docker-compile#2]
Renovations
- The repository for ipxe changed - ipxe was complainging with an error that no longer exists;
- Using debian:bullseye

"Features"
- Show output from build script
  - Helps to know that the container is working, especially when using this for the first time.
  - Helps to know when it finished.
- add 'runDocker.sh'
  - Makes it easier to run and rerun - also uses modern docker compose.
  - Added comment to show how to scp the result to a target server
    - Helps to understand where one of the output files is located exactly.
- Use local git copy as the context (docker-compose.yml).
  - I made several updates to the build script/Dockerfile without any effect until I saw that the context was the remote git repository.

**Comment by madic-creates** [comment]
Added some of your suggestions in 4c830caeb654d0bcbd10e6eb4a9790d3930c39f8 and 975f860eb5de1d94fd91ba92118ef20ce779f3fa
